<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;

Route::get('/', function () {
    return redirect()->route('companies.index');
});


Auth::routes([
    'register' => false,
    'reset'    => true,  
    'verify'   => false,
]);

// Protected Admin Panel Routes
Route::middleware(['auth'])->group(function () {
    
    // Redirect standard /home (generated by laravel/ui) to companies list
    Route::get('/home', function () {
        return redirect()->route('companies.index');
    })->name('home');

    // Companies Resource Routes (index, create, store, show, edit, update, destroy)
    Route::resource('companies', CompanyController::class);

    // Employees Resource Routes (index, create, store, show, edit, update, destroy)
    Route::resource('employees', EmployeeController::class);
});